name: File issues in new tool
description: Please open your docs issue [there](https://google.com).
body:
  - type: markdown
    attributes:
      value: |
        We no longer use the repo to file and track issues. Please use the new tool.
  - type: input
    attributes:
      label: Contact us with questions
      description: How can you get in touch if you need more info?
      placeholder: Ping us in `#our-channel`
    validations:
      required: false
